project_id = "remrjowcbyavydfbkbny"

[auth.hook.send_email]
  enabled = true
  uri = "https://remrjowcbyavydfbkbny.supabase.co/functions/v1/auth-email-hook"
  secrets = "env(SEND_EMAIL_HOOK_SECRET)"

[functions]
  [functions.admin-manage-users]
    verify_jwt = false
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.check-expired-subscriptions]
    verify_jwt = false
  [functions.guru-webhook]
    verify_jwt = false
  [functions.meta-capi]
    verify_jwt = false
